"""IngestFilter: deterministic business-meaning filtering (spec 2026-07-06)."""

from pathlib import Path

from opendomainmcp.ingest.filters import IngestFilter, _parse_exclude_spec


def test_default_excludes_match_test_and_lock_files(tmp_path):
    flt = IngestFilter()
    root = tmp_path
    assert flt.exclusion_reason(root / "src" / "test_billing.py", root) == "test_*.py"
    assert flt.exclusion_reason(root / "app" / "billing.spec.ts", root) == "*.spec.ts"
    assert (
        flt.exclusion_reason(root / "package-lock.json", root) == "package-lock.json"
    )
    assert flt.exclusion_reason(root / "static" / "app.min.js", root) == "*.min.js"


def test_directory_patterns_match_any_segment(tmp_path):
    flt = IngestFilter()
    root = tmp_path
    assert flt.exclusion_reason(root / "tests" / "helper.py", root) == "tests/"
    assert flt.exclusion_reason(root / "pkg" / "vendor" / "lib.go", root) == "vendor/"
    assert flt.exclusion_reason(root / "db" / "migrations" / "0001.sql", root) == "migrations/"
    # A *file* named like a dir pattern is not a directory match.
    assert flt.exclusion_reason(root / "src" / "vendor", root) is None


def test_business_files_pass(tmp_path):
    flt = IngestFilter()
    root = tmp_path
    for rel in ("src/billing.py", "src/OrderService.java", "docs/pricing.md",
                "frontend/checkout.ts"):
        assert flt.exclusion_reason(root / Path(rel), root) is None


def test_extra_excludes_layer_over_defaults(tmp_path):
    flt = IngestFilter(extra_excludes=("*.sql", "legacy/"))
    root = tmp_path
    assert flt.exclusion_reason(root / "proc" / "billing.sql", root) == "*.sql"
    assert flt.exclusion_reason(root / "legacy" / "old.java", root) == "legacy/"
    # defaults still apply
    assert flt.exclusion_reason(root / "test_x.py", root) == "test_*.py"


def test_no_defaults_mode_keeps_only_user_rules(tmp_path):
    flt = IngestFilter(extra_excludes=("*.sql",), use_defaults=False)
    root = tmp_path
    assert flt.exclusion_reason(root / "test_x.py", root) is None
    assert flt.exclusion_reason(root / "a.sql", root) == "*.sql"


def test_parse_exclude_spec_splits_commas_and_newlines():
    assert _parse_exclude_spec("*.sql, legacy/\n*.tmp\n\n") == [
        "*.sql", "legacy/", "*.tmp"
    ]
    assert _parse_exclude_spec("") == []


def test_generated_marker_in_head_is_filtered(tmp_path):
    f = tmp_path / "Model.java"
    f.write_text("// Code generated by protoc-gen. DO NOT EDIT.\nclass Model {}\n")
    assert IngestFilter().exclusion_reason(f, tmp_path) == "generated-marker"


def test_generated_marker_is_case_insensitive_and_at_generated(tmp_path):
    f = tmp_path / "api.ts"
    f.write_text("/* @GENERATED by codegen */\nexport const x = 1\n")
    assert IngestFilter().exclusion_reason(f, tmp_path) == "generated-marker"


def test_marker_beyond_head_lines_is_not_sniffed(tmp_path):
    f = tmp_path / "billing.py"
    f.write_text("\n" * 15 + "# do not edit this section by hand\n")
    assert IngestFilter().exclusion_reason(f, tmp_path) is None


def test_no_defaults_mode_disables_sniff(tmp_path):
    f = tmp_path / "gen.py"
    f.write_text("# autogenerated\n")
    flt = IngestFilter(use_defaults=False)
    assert flt.exclusion_reason(f, tmp_path) is None


def test_missing_file_does_not_raise(tmp_path):
    # exclusion_reason may be probed on paths that vanish mid-run
    assert IngestFilter().exclusion_reason(tmp_path / "gone.py", tmp_path) is None


def test_from_settings_layers_setting_and_run_excludes(tmp_path):
    from opendomainmcp.config import Settings

    settings = Settings(ingest_exclude="*.sql, legacy/")
    flt = IngestFilter.from_settings(settings, extra_excludes=("*.tmp",))
    root = tmp_path
    assert flt.exclusion_reason(root / "p.sql", root) == "*.sql"        # setting
    assert flt.exclusion_reason(root / "x.tmp", root) == "*.tmp"        # per-run
    assert flt.exclusion_reason(root / "test_a.py", root) == "test_*.py"  # built-in


def test_ingest_exclude_is_runtime_editable():
    from opendomainmcp.config import EDITABLE_FIELDS

    assert "ingest_exclude" in EDITABLE_FIELDS
